name: RequiredChecks
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule: 
    - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Run Required Check
        run: echo Hello from required org action
      - name: List Runners
        run : gh api /orgs/devops-testbed/actions/runners
