name: RequiredChecks
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  pull_request_review:
  workflow_dispatch:
  schedule: 
    - cron: "0 12 1/14 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      GH_TOKEN: ${{ github.token }}
      REPO: ${{ github.repository }}
    permissions: write-all
    steps:
      - name: Run Required Check
        run: echo Hello from required org action
      - name: List Runners
        run : gh api /repos/$REPO/actions/runners || echo 0
